2015/06/14 15:00:07 [error] 5#0: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unable to write in the logs directory (/var/www/symfony/app/logs)
' in /var/www/symfony/app/bootstrap.php.cache:2659
Stack trace:
#0 /var/www/symfony/app/bootstrap.php.cache(2617): Symfony\Component\HttpKernel\Kernel->buildContainer()
#1 /var/www/symfony/app/bootstrap.php.cache(2396): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#2 /var/www/symfony/app/bootstrap.php.cache(2427): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/symfony/web/app.php(28): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#4 {main}
  thrown in /var/www/symfony/app/bootstrap.php.cache on line 2659" while reading response header from upstream, client: 172.17.42.1, server: symfony.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://172.17.0.105:9000", host: "localhost"
2015/06/14 15:01:05 [error] 5#0: *4 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unable to write in the logs directory (/var/www/symfony/app/logs)
' in /var/www/symfony/app/bootstrap.php.cache:2659
Stack trace:
#0 /var/www/symfony/app/bootstrap.php.cache(2617): Symfony\Component\HttpKernel\Kernel->buildContainer()
#1 /var/www/symfony/app/bootstrap.php.cache(2396): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#2 /var/www/symfony/app/bootstrap.php.cache(2427): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/symfony/web/app.php(28): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#4 {main}
  thrown in /var/www/symfony/app/bootstrap.php.cache on line 2659" while reading response header from upstream, client: 172.17.42.1, server: symfony.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://172.17.0.105:9000", host: "localhost"
2015/06/14 15:04:51 [error] 5#0: *9 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unable to write in the logs directory (/var/www/symfony/app/logs)
' in /var/www/symfony/app/bootstrap.php.cache:2659
Stack trace:
#0 /var/www/symfony/app/bootstrap.php.cache(2617): Symfony\Component\HttpKernel\Kernel->buildContainer()
#1 /var/www/symfony/app/bootstrap.php.cache(2396): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#2 /var/www/symfony/app/bootstrap.php.cache(2427): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/symfony/web/app.php(28): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#4 {main}
  thrown in /var/www/symfony/app/bootstrap.php.cache on line 2659" while reading response header from upstream, client: 172.17.42.1, server: symfony.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://172.17.0.105:9000", host: "localhost"
2015/06/14 15:04:56 [error] 5#0: *9 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unable to write in the logs directory (/var/www/symfony/app/logs)
' in /var/www/symfony/app/bootstrap.php.cache:2659
Stack trace:
#0 /var/www/symfony/app/bootstrap.php.cache(2617): Symfony\Component\HttpKernel\Kernel->buildContainer()
#1 /var/www/symfony/app/bootstrap.php.cache(2396): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#2 /var/www/symfony/app/bootstrap.php.cache(2427): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/symfony/web/app.php(28): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#4 {main}
  thrown in /var/www/symfony/app/bootstrap.php.cache on line 2659" while reading response header from upstream, client: 172.17.42.1, server: symfony.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://172.17.0.105:9000", host: "localhost"
2015/06/14 15:06:51 [error] 11#0: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unable to write in the logs directory (/var/www/symfony/app/logs)
' in /var/www/symfony/app/bootstrap.php.cache:2659
Stack trace:
#0 /var/www/symfony/app/bootstrap.php.cache(2617): Symfony\Component\HttpKernel\Kernel->buildContainer()
#1 /var/www/symfony/app/bootstrap.php.cache(2396): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#2 /var/www/symfony/app/bootstrap.php.cache(2427): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/symfony/web/app.php(28): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#4 {main}
  thrown in /var/www/symfony/app/bootstrap.php.cache on line 2659" while reading response header from upstream, client: 172.17.42.1, server: symfony.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://172.17.0.112:9000", host: "localhost"
2015/06/14 15:07:49 [error] 5#0: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unable to write in the logs directory (/var/www/symfony/app/logs)
' in /var/www/symfony/app/bootstrap.php.cache:2659
Stack trace:
#0 /var/www/symfony/app/bootstrap.php.cache(2617): Symfony\Component\HttpKernel\Kernel->buildContainer()
#1 /var/www/symfony/app/bootstrap.php.cache(2396): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#2 /var/www/symfony/app/bootstrap.php.cache(2427): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/symfony/web/app.php(28): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#4 {main}
  thrown in /var/www/symfony/app/bootstrap.php.cache on line 2659" while reading response header from upstream, client: 172.17.42.1, server: symfony.dev, request: "GET /hello/cesar HTTP/1.1", upstream: "fastcgi://172.17.0.120:9000", host: "localhost"
2015/06/14 15:08:26 [error] 5#0: *3 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unable to write in the logs directory (/var/www/symfony/app/logs)
' in /var/www/symfony/app/bootstrap.php.cache:2659
Stack trace:
#0 /var/www/symfony/app/bootstrap.php.cache(2617): Symfony\Component\HttpKernel\Kernel->buildContainer()
#1 /var/www/symfony/app/bootstrap.php.cache(2396): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#2 /var/www/symfony/app/bootstrap.php.cache(2427): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/symfony/web/app.php(28): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#4 {main}
  thrown in /var/www/symfony/app/bootstrap.php.cache on line 2659" while reading response header from upstream, client: 172.17.42.1, server: symfony.dev, request: "GET /app/example HTTP/1.1", upstream: "fastcgi://172.17.0.120:9000", host: "localhost"
2015/06/14 15:09:56 [error] 5#0: *5 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unable to write in the logs directory (/var/www/symfony/app/logs)
' in /var/www/symfony/app/bootstrap.php.cache:2659
Stack trace:
#0 /var/www/symfony/app/bootstrap.php.cache(2617): Symfony\Component\HttpKernel\Kernel->buildContainer()
#1 /var/www/symfony/app/bootstrap.php.cache(2396): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#2 /var/www/symfony/app/bootstrap.php.cache(2427): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/symfony/web/app.php(28): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#4 {main}
  thrown in /var/www/symfony/app/bootstrap.php.cache on line 2659" while reading response header from upstream, client: 172.17.42.1, server: symfony.dev, request: "GET /app/example HTTP/1.1", upstream: "fastcgi://172.17.0.120:9000", host: "localhost"
2015/06/14 15:10:56 [error] 5#0: *7 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unable to write in the logs directory (/var/www/symfony/app/logs)
' in /var/www/symfony/app/bootstrap.php.cache:2659
Stack trace:
#0 /var/www/symfony/app/bootstrap.php.cache(2617): Symfony\Component\HttpKernel\Kernel->buildContainer()
#1 /var/www/symfony/app/bootstrap.php.cache(2396): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#2 /var/www/symfony/app/bootstrap.php.cache(2427): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/symfony/web/app.php(28): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#4 {main}
  thrown in /var/www/symfony/app/bootstrap.php.cache on line 2659" while reading response header from upstream, client: 172.17.42.1, server: symfony.dev, request: "GET /app/example HTTP/1.1", upstream: "fastcgi://172.17.0.120:9000", host: "localhost"
2015/06/14 15:11:13 [error] 5#0: *9 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unable to write in the logs directory (/var/www/symfony/app/logs)
' in /var/www/symfony/app/bootstrap.php.cache:2659
Stack trace:
#0 /var/www/symfony/app/bootstrap.php.cache(2617): Symfony\Component\HttpKernel\Kernel->buildContainer()
#1 /var/www/symfony/app/bootstrap.php.cache(2396): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#2 /var/www/symfony/app/bootstrap.php.cache(2427): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/symfony/web/app.php(28): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#4 {main}
  thrown in /var/www/symfony/app/bootstrap.php.cache on line 2659" while reading response header from upstream, client: 172.17.42.1, server: symfony.dev, request: "GET /app/example HTTP/1.1", upstream: "fastcgi://172.17.0.120:9000", host: "localhost"
2015/06/14 15:11:21 [error] 5#0: *9 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unable to write in the logs directory (/var/www/symfony/app/logs)
' in /var/www/symfony/app/bootstrap.php.cache:2659
Stack trace:
#0 /var/www/symfony/app/bootstrap.php.cache(2617): Symfony\Component\HttpKernel\Kernel->buildContainer()
#1 /var/www/symfony/app/bootstrap.php.cache(2396): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#2 /var/www/symfony/app/bootstrap.php.cache(2427): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/symfony/web/app.php(28): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#4 {main}
  thrown in /var/www/symfony/app/bootstrap.php.cache on line 2659" while reading response header from upstream, client: 172.17.42.1, server: symfony.dev, request: "GET /app/example HTTP/1.1", upstream: "fastcgi://172.17.0.120:9000", host: "localhost"
2015/06/14 15:22:46 [error] 5#0: *12 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unable to write in the logs directory (/var/www/symfony/app/logs)
' in /var/www/symfony/app/bootstrap.php.cache:2659
Stack trace:
#0 /var/www/symfony/app/bootstrap.php.cache(2617): Symfony\Component\HttpKernel\Kernel->buildContainer()
#1 /var/www/symfony/app/bootstrap.php.cache(2396): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#2 /var/www/symfony/app/bootstrap.php.cache(2427): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/symfony/web/app.php(28): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#4 {main}
  thrown in /var/www/symfony/app/bootstrap.php.cache on line 2659" while reading response header from upstream, client: 172.17.42.1, server: symfony.dev, request: "GET /app/example HTTP/1.1", upstream: "fastcgi://172.17.0.120:9000", host: "localhost"
2015/06/14 15:22:57 [error] 5#0: *12 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unable to write in the logs directory (/var/www/symfony/app/logs)
' in /var/www/symfony/app/bootstrap.php.cache:2659
Stack trace:
#0 /var/www/symfony/app/bootstrap.php.cache(2617): Symfony\Component\HttpKernel\Kernel->buildContainer()
#1 /var/www/symfony/app/bootstrap.php.cache(2396): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#2 /var/www/symfony/app/bootstrap.php.cache(2427): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/symfony/web/app.php(28): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#4 {main}
  thrown in /var/www/symfony/app/bootstrap.php.cache on line 2659" while reading response header from upstream, client: 172.17.42.1, server: symfony.dev, request: "GET /app/example HTTP/1.1", upstream: "fastcgi://172.17.0.120:9000", host: "localhost"
2015/06/14 15:23:01 [error] 5#0: *12 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unable to write in the logs directory (/var/www/symfony/app/logs)
' in /var/www/symfony/app/bootstrap.php.cache:2659
Stack trace:
#0 /var/www/symfony/app/bootstrap.php.cache(2617): Symfony\Component\HttpKernel\Kernel->buildContainer()
#1 /var/www/symfony/app/bootstrap.php.cache(2396): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#2 /var/www/symfony/app/bootstrap.php.cache(2427): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/symfony/web/app.php(28): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#4 {main}
  thrown in /var/www/symfony/app/bootstrap.php.cache on line 2659" while reading response header from upstream, client: 172.17.42.1, server: symfony.dev, request: "GET /app/example HTTP/1.1", upstream: "fastcgi://172.17.0.120:9000", host: "localhost"
2015/06/14 15:23:10 [error] 5#0: *12 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unable to write in the logs directory (/var/www/symfony/app/logs)
' in /var/www/symfony/app/bootstrap.php.cache:2659
Stack trace:
#0 /var/www/symfony/app/bootstrap.php.cache(2617): Symfony\Component\HttpKernel\Kernel->buildContainer()
#1 /var/www/symfony/app/bootstrap.php.cache(2396): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#2 /var/www/symfony/app/bootstrap.php.cache(2427): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/symfony/web/app.php(28): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#4 {main}
  thrown in /var/www/symfony/app/bootstrap.php.cache on line 2659" while reading response header from upstream, client: 172.17.42.1, server: symfony.dev, request: "GET /app/example HTTP/1.1", upstream: "fastcgi://172.17.0.120:9000", host: "localhost"
2015/06/14 15:23:41 [error] 5#0: *17 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unable to write in the logs directory (/var/www/symfony/app/logs)
' in /var/www/symfony/app/bootstrap.php.cache:2659
Stack trace:
#0 /var/www/symfony/app/bootstrap.php.cache(2617): Symfony\Component\HttpKernel\Kernel->buildContainer()
#1 /var/www/symfony/app/bootstrap.php.cache(2396): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#2 /var/www/symfony/app/bootstrap.php.cache(2427): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/symfony/web/app.php(28): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#4 {main}
  thrown in /var/www/symfony/app/bootstrap.php.cache on line 2659" while reading response header from upstream, client: 172.17.42.1, server: symfony.dev, request: "GET /demo HTTP/1.1", upstream: "fastcgi://172.17.0.120:9000", host: "localhost"
2015/06/14 15:23:43 [error] 5#0: *17 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unable to write in the logs directory (/var/www/symfony/app/logs)
' in /var/www/symfony/app/bootstrap.php.cache:2659
Stack trace:
#0 /var/www/symfony/app/bootstrap.php.cache(2617): Symfony\Component\HttpKernel\Kernel->buildContainer()
#1 /var/www/symfony/app/bootstrap.php.cache(2396): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#2 /var/www/symfony/app/bootstrap.php.cache(2427): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/symfony/web/app.php(28): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#4 {main}
  thrown in /var/www/symfony/app/bootstrap.php.cache on line 2659" while reading response header from upstream, client: 172.17.42.1, server: symfony.dev, request: "GET /demo HTTP/1.1", upstream: "fastcgi://172.17.0.120:9000", host: "localhost"
2015/06/14 15:24:14 [error] 5#0: *20 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unable to write in the logs directory (/var/www/symfony/app/logs)
' in /var/www/symfony/app/bootstrap.php.cache:2659
Stack trace:
#0 /var/www/symfony/app/bootstrap.php.cache(2617): Symfony\Component\HttpKernel\Kernel->buildContainer()
#1 /var/www/symfony/app/bootstrap.php.cache(2396): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#2 /var/www/symfony/app/bootstrap.php.cache(2427): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/symfony/web/app.php(28): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#4 {main}
  thrown in /var/www/symfony/app/bootstrap.php.cache on line 2659" while reading response header from upstream, client: 172.17.42.1, server: symfony.dev, request: "GET /demo HTTP/1.1", upstream: "fastcgi://172.17.0.120:9000", host: "localhost"
2015/06/14 15:25:19 [error] 5#0: *22 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unable to write in the logs directory (/var/www/symfony/app/logs)
' in /var/www/symfony/app/bootstrap.php.cache:2659
Stack trace:
#0 /var/www/symfony/app/bootstrap.php.cache(2617): Symfony\Component\HttpKernel\Kernel->buildContainer()
#1 /var/www/symfony/app/bootstrap.php.cache(2396): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#2 /var/www/symfony/app/bootstrap.php.cache(2427): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/symfony/web/app.php(28): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#4 {main}
  thrown in /var/www/symfony/app/bootstrap.php.cache on line 2659" while reading response header from upstream, client: 172.17.42.1, server: symfony.dev, request: "GET /demo HTTP/1.1", upstream: "fastcgi://172.17.0.120:9000", host: "localhost"
